# PersistentVolume (cluster-scoped, no namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---

# PersistentVolumeClaim (namespaced)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: cuny-volumes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi



