apiVersion: batch/v1
kind: Job
metadata:
  namespace: cuny-jobs
  name: hello-job
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["/bin/sh", "-c", "echo Hello from Job!"]
    restartPolicy: Never
