apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: cuny-docker
spec:
  selector:
    app: hello-cst
  ports:
    - name: http
      port: 80          # Service port (what clients connect to)
      targetPort: 5000  # Pod's containerPort
  type: LoadBalancer
