apiVersion: v1
kind: Pod
metadata:
  namespace: cuny-volumes
  name: hostpath-pod
spec:
  containers:
  - name: logger
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello from HostPath' | tee -a /host/data.txt >&2; sleep 3600"]
    volumeMounts:
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp/demo-data
      type: DirectoryOrCreate
