apiVersion: v1
kind: Pod
metadata:
  namespace: cuny-volumes
  name: shared-volume-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello from writer' | tee /data/message.txt >&2; sleep 3600"]
    volumeMounts:
    - name: shared-storage
      mountPath: /data

  - name: reader
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Reader sees:'; cat /data/message.txt | tee >&2; sleep 3600"]
    volumeMounts:
    - name: shared-storage
      mountPath: /data

  volumes:
  - name: shared-storage
    emptyDir: {}
