apiVersion: v1
kind: Pod
metadata:
  namespace: cuny-volumes
  name: shared-volume-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c", "echo Hello from writer > /data/message.txt; sleep 3600"]
    volumeMounts:
    - name: shared-storage
      mountPath: /data

  - name: reader
    image: busybox
    command: ["/bin/sh", "-c", "cat /data/message.txt; sleep 3600"]
    volumeMounts:
    - name: shared-storage
      mountPath: /data

  volumes:
  - name: shared-storage
    emptyDir: {}
