apiVersion: v1
kind: Pod
metadata:
  namespace: multicon-pods
  name: my-sidecar-pod
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80

  - name: sidecar-logger
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo logging...; sleep 5; done"]

