apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy-recreate
  namespace: cuny-deploy
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web-recreate
  template:
    metadata:
      labels:
        app: web-recreate
    spec:
      containers:
        - name: web-container
          image: nginx:1.25
